### ISSUE TITLE
Cannot use .push

### ISSUE THREAD

**Issue by antononcube** [lizmat/Hash-int#1]
The following code :

```perl6
use Hash::int;
my %hash0 is Hash::int = 42 => "foo", 666 => "bar";
%hash0.push: (23 => 'new');
```

gives the error:

> Cannot resolve caller push(Hash::int: Pair:D); none of these signatures match:
>    (Any:U \SELF: |values) 
>    [...]

**Comment by lizmat** [comment]
Thanks for the report.  `.push` has been added with the latest release.
